# Generated by Django 4.0.10 on 2023-05-10 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('ML', 'Male'), ('FE', 'Female')], max_length=2)),
                ('job', models.CharField(max_length=150)),
                ('marriageStatus', models.CharField(choices=[('MA', 'Married'), ('SN', 'Signle'), ('WO', 'Widowed')], max_length=2)),
                ('birthDate', models.DateField()),
                ('nationalID', models.CharField(max_length=14)),
                ('nationalIDExpiration', models.DateField()),
                ('qualification', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=150)),
                ('gaurdianName', models.CharField(max_length=255)),
                ('gaurdianRelation', models.CharField(choices=[('MA', 'Married'), ('SN', 'Signle'), ('WO', 'Widowed')], max_length=2)),
                ('gaudrianNumber', models.CharField(max_length=150)),
                ('housing', models.CharField(max_length=255)),
                ('caseDescribtion', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
