# Generated by Django 4.0.10 on 2023-05-10 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_case_gaurdianrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='addDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
