# Generated by Django 4.0.10 on 2023-05-13 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_adddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humanNeeds', models.CharField(max_length=300)),
                ('otherHelp', models.CharField(max_length=300)),
                ('interviewDescription', models.CharField(max_length=300)),
                ('interviewResult', models.CharField(max_length=300)),
                ('researcherOpinion', models.CharField(max_length=300)),
                ('supervisorOpinion', models.CharField(max_length=300)),
                ('overallRating', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('diseaseType', models.CharField(choices=[('ML', 'Male'), ('FE', 'Female')], max_length=2)),
                ('medicine', models.CharField(max_length=150)),
                ('insuranceID', models.IntegerField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Family_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('ML', 'Male'), ('FE', 'Female')], max_length=2)),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(choices=[('HS', 'High School'), ('BA', 'Bachelor')], max_length=2)),
                ('occubation', models.CharField(max_length=150)),
                ('notes', models.CharField(max_length=150)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Family_Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Family_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('notes', models.CharField(max_length=150)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
    ]
