# Generated by Django 4.0.10 on 2023-05-14 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_regions_typehelp_case_typehelp_alter_case_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='typeHelp',
        ),
        migrations.AlterField(
            model_name='case',
            name='region',
            field=models.CharField(choices=[('BJ', 'Borj Al Arab'), ('AX', 'Alexandria')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
