# Generated by Django 4.0.10 on 2023-05-13 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_notes_medical_expenses_family_member_family_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='region',
            field=models.CharField(choices=[('BJ', 'Borj Al Arab'), ('AX', 'Alexandria')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
