# Generated by Django 4.0.10 on 2023-05-14 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_remove_case_typehelp_alter_case_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='typeHelp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.typehelp'),
        ),
        migrations.AlterField(
            model_name='case',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.regions'),
        ),
    ]
